image: golang:latest

stages:
  - version
  - build

increment_version:
  stage: version
  before_script:
    - if [[ $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ major ]]; then
        BUMP_VERSION=major;
      elif [[ $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ feature ]]; then
        BUMP_VERSION=minor;
      else
        BUMP_VERSION=patch;
      fi
  script:
    - ./versione bump $BUMP_VERSION -v $(git describe --tags --abbrev=0) > new_version
  artifacts:
    paths:
      - new_version
    expire_in: 1 hour

compile:
  stage: build
  before_script:
    - versao=`cat ./new_version`
  script:
    - go build -ldflags="-X 'gitlab.com/allanfs/versione/cmd.Version=$versao'" -o versione main.go
  dependencies:
    - increment_version
  artifacts:
    paths:
      - versione
    expire_in: 2 hrs